'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('../backend/node_modules/jsdom');
const root=path.join(__dirname,'..');
async function settled(fn){for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('UI did not settle');}
test('intake UI reviews safely, archives, restores and converts with confirmed address',async()=>{
 const id='00000000-0000-4000-8000-000000000001',lead={id,kind:'service',status:'new',data:{name:'<img src=x onerror=alert(1)>',phone:'917-555-0100',email:'lead@example.test',address:'10 Main St',town:'Old Bridge',system:'Heating',message:'No heat'},created_at:'2026-10-02',internal_notes:''},calls=[];
 const dom=new JSDOM(fs.readFileSync(root+'/backend/accounts/views/dashboard.html','utf8'),{url:'https://test.example/account/admin#inquiries',runScripts:'outside-only'}),w=dom.window,$=s=>w.document.querySelector(s);
 w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.fetch=async(url,opts)=>{const route=new URL(url,'https://test.example').pathname.replace('/api/account/',''),body=opts.body?JSON.parse(opts.body):undefined;calls.push({route,body});let data={ok:true};if(route==='session')data={...data,account:{role:'admin',name:'Admin',email:'admin@example.test'},csrfToken:'fixture'};else if(route==='admin/inquiries'&&body)data.id=id;else if(route==='admin/inquiries')data={...data,inquiries:[lead],total:1,page:1};else if(route==='admin/inquiries/'+id){lead.status=body.status;lead.internal_notes=body.internal_notes;}else if(route.endsWith('/convert'))data.id=id;else if(route==='admin/accounts')data.accounts=[{id,name:'Existing',email:'lead@example.test',state:'active'}];else if(route==='admin/requests')data={...data,requests:[],page:1,total:0};else if(route==='admin/requests/'+id)data.request={id,account_id:id,service:'Heating repair',status:'requested',name:'Existing',email:'lead@example.test',line1:'10 Main St',city:'Old Bridge',created_at:'2026-10-02'};else throw Error('Unexpected '+route);return {ok:true,status:200,json:async()=>data};};
 for(const f of ['operations','billing','scheduling','inquiries','portal'])w.eval(fs.readFileSync(root+'/site/'+f+'.js','utf8'));
 try{await settled(()=>!!$('[data-inquiry]'));assert.equal($('#content img'),null);$('[data-inquiry]').click();$('#inquiry-status').value='archived';$('#inquiry-state').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>!$('#detail-dialog').open);$('[data-inquiry]').click();assert($('#convert-inquiry').disabled);$('#inquiry-status').value='new';$('#inquiry-state').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>!$('#detail-dialog').open);$('[data-inquiry]').click();$('#convert-inquiry').click();assert.equal($('#service').value,'Heating repair');assert.equal($('#line1').value,'10 Main St');$('#find-customer').click();await settled(()=>$('#account_id').options.length===2);$('#account_id').value=id;$('#postal_code').value='08857';$('#convert-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>!!$('#review-form'));const call=calls.find(c=>c.route.endsWith('/convert'));assert.equal(call.body.account_id,id);assert.equal(call.body.postal_code,'08857');assert.equal(call.body.description,'No heat');}finally{w.close();}
});
