'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('../backend/node_modules/jsdom');const {randomUUID}=require('node:crypto');const root=require('node:path').join(__dirname,'..');
async function settled(w,fn){for(let n=0;n<100;n++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('UI did not settle: '+w.document.querySelector('#notice').textContent);}
test('scheduling agenda books, preserves private fields, links contacts, and adds a phone request',async()=>{
 const customer={id:randomUUID(),name:'Alex <Example>',email:'alex@example.test',phone:'202-555-0100'};const r={id:randomUUID(),account_id:customer.id,...customer,service:'Diagnosis',description:'No heat',line1:'100 Main St',city:'Old Bridge',status:'reviewing',internal_notes:'PRIVATE',customer_update:'Existing update',priority:'urgent',follow_up_on:'2030-10-01'};r.id=randomUUID();let visits=[],queue=[r],calls=[];
 const dom=new JSDOM(fs.readFileSync(root+'/backend/accounts/views/dashboard.html','utf8'),{url:'https://fixture.example/account/admin#schedule',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,$=s=>w.document.querySelector(s);w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.confirm=()=>true;
 w.fetch=async(url,opts)=>{const u=new URL(url,'https://fixture.example'),route=u.pathname.replace('/api/account/',''),body=opts.body?JSON.parse(opts.body):undefined;calls.push({route,body});let result={ok:true};
 if(route==='session')result={...result,account:{...customer,role:'admin'},csrfToken:'fixture'};
 else if(route==='admin/schedule')result={...result,requests:visits,total:visits.length,page:1,summary:{today:0,overdue:0,needs_booking:queue.length}};
 else if(route==='admin/requests'&&!body)result={...result,requests:queue,total:queue.length,page:1};
 else if(route==='admin/requests/'+r.id){Object.assign(r,body);visits=[r];queue=[];result.email='sent';}
 else if(route==='admin/accounts')result.accounts=[customer];
 else if(route==='admin/accounts/'+customer.id)result={...result,account:customer,addresses:[{id:'address-fixture',line1:'100 Main St',city:'Old Bridge'}]};
 else if(route==='admin/requests'&&body)result.id=randomUUID();
 else throw Error('Unexpected route '+route);
 return {ok:true,status:200,json:async()=>result};};
 for(const file of ['operations.js','billing.js','scheduling.js','portal.js'])w.eval(fs.readFileSync(root+'/site/'+file,'utf8'));
 await settled(w,()=>!!$('[data-book]'));assert.equal($('#portal-nav [href="#schedule"]').getAttribute('aria-current'),'page');assert.match($('#content').textContent,/Alex <Example>/);assert(!$('#content').textContent.includes('PRIVATE'));assert.equal($('a[href^="tel:"]').getAttribute('href'),'tel:+19176083201');assert($('a[href="tel:2025550100"]'));assert($('a[href="sms:2025550100"]'));assert($('a[href^="mailto:"]'));assert($('a[href^="https://www.google.com/maps"]'));
 $('[data-book]').click();assert.equal($('#booking-update').value,'Existing update');$('#appointment_at').value='2030-10-01T10:30';$('#booking-update').value='Confirmed visit';$('#booking-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(w,()=>!!$('[data-calendar]'));const patch=calls.find(c=>c.route==='admin/requests/'+r.id);assert.equal(patch.body.status,'scheduled');assert.equal(patch.body.customer_update,'Confirmed visit');assert.equal(patch.body.internal_notes,undefined);assert.equal(r.internal_notes,'PRIVATE');assert.equal(r.priority,'urgent');assert.equal(r.follow_up_on,'2030-10-01');assert.match($('#notice').textContent,/Customer email sent/);
 $('[data-review]').click();assert.equal($('#internal_notes').value,'PRIVATE');$('#detail-dialog').close();
 $('#add-phone-request').click();$('#intake-query').value='Alex';$('#intake-search').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(w,()=>!!$('[data-intake-customer]'));$('[data-intake-customer]').click();await settled(w,()=>!!$('#intake-form'));$('#intake-description').value='Phone call about noisy furnace';$('#intake-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(w,()=>$('#notice').textContent.includes('No email sent yet'));const intake=calls.find(c=>c.route==='admin/requests'&&c.body);assert.equal(intake.body.account_id,customer.id);assert.equal(intake.body.description,'Phone call about noisy furnace');dom.window.close();
});
